[package]
name = "advent14"
version = "0.1.0"
authors = ["owen.morgan <owen.morgan@ultraleap.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
either = "1.6.1"